#!/bin/bash

# ZUGBRUECKE
# Calling routines in Windows DLLs from Python scripts running on unixlike systems
# https://github.com/pleiszenburg/zugbruecke
#
#	scripts/wenv: Running Python on Wine using zugbruecke's configuration
#
#	Required to run on platform / side: [UNIX]
#
# 	Copyright (C) 2017-2019 Sebastian M. Ernst <ernst@pleiszenburg.de>
#
# <LICENSE_BLOCK>
# The contents of this file are subject to the GNU Lesser General Public License
# Version 2.1 ("LGPL" or "License"). You may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
# https://github.com/pleiszenburg/zugbruecke/blob/master/LICENSE
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the
# specific language governing rights and limitations under the License.
# </LICENSE_BLOCK>

conf=$(python3 -m zugbruecke.wenv $1 --configure)
param=$(printf "%q" "${@:2}")

IFS="#"
for segment in $conf; do
	if [[ $segment == ___* ]] ; then # is this a command?
		cmd="${segment:7}" # strip command prefix
		if [[ $segment == ___1___* ]] ; then # keep options?
			if [ "$#" -gt 1 ]; then # are there arguments?
				eval "$cmd $param" # run interactive command with options
			else
				eval "$cmd"
			fi
		else
			eval "$cmd" # run interactive command without options
		fi
	else
		varname=$(echo $segment | cut -d '=' -f1)
		vardata=$(echo $segment | cut -d '=' -f2)
		export $varname=$vardata # export environment variable
	fi
done
